### ISSUE TITLE
Add FlowNode identifier and FlowAsset update delegate

### ISSUE THREAD

**Issue by moadib** [MothCocoon/Flow#27]
I think it would be useful to be able to check the state of the FlowNode by id, for example. I can call GetRecordedNodes, GetActiveNodes and check if it contains a node with a specific id.

I can add custom nodes to set something somewhere, but standard nodes like AND / OR  also can be traited as task status.

In short, if I use FlowAsset as Quest, then besides ACTIVE / COMPLETED I want to check intermediate state too.

**Comment by MothDoctor** [comment]
Well... I don't really see why nodes AND/OR would expose their state anywhere? These nodes control their state internally.

If I properly understand that, I think it would be better to simply create a Quest Asset extending Flow Asset. And create quest-specific nodes that would operate on Quest Asset properties. This way you are free to define their quest-specific enums for your game without using workarounds like abstract ID - it would have to be integer, bitfield or gameplay tag.

If you would encounter any issues with that, it possible the current plugin's code is lacking in this area. I'm planning to focus on this in the next plugin version (v1.2, not the upcoming v1.1).
https://github.com/MothCocoon/Flow/issues/1

Obviously, perhaps I didn't understand probably your request. So leaving this ticket opened until you'd clarify if you really need changes in the plugin here :)

**Comment by moadib** [comment]
Let's take simple quest - interacting with actorA & actorB and then moving to specific point leads to activation of totem.

It is two observing nodes, one operator and one actor notify. 

In your case we also should add custom quest state writing nodes after each observing node and another one after operator which transform simple graph to something more complicate.

Anyway it was just proposal :)

**Comment by MothDoctor** [comment]
> In your case we also should add custom quest state writing nodes after each observing node and another one after operator which transform simple graph to something more complicate.

Yup, from my experience there's always needed a method/node like "Set quest to Failed/Success" or something like that :)
I used to have a separate Journal asset - this what is used to be displayed in the game's UI. With objective, objective states and general quest state. It allows many graphs (Flow Graph or any other) to modify a single Journal quest. Or update many Journal quests from a single graph.

Obviously, I'm always open to learning other approaches. It already happened that I change my mind about some Flow feature. Don't hesitate to bother me :)
Although Flow Discord server might a better place to converse loosely.

**Comment by moadib** [comment]
Invite link for Discord invalid or expired :)

**Comment by MothDoctor** [comment]
> 
> 
> Invite link for Discord invalid or expired :)

https://discord.gg/93wjQWJR :)
